apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qat-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: qat
            path: k8s/overlays/qat

  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: devops-project

      source:
        repoURL: https://github.com/kamal-singh17/devops-assignment
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
